# Generated by Django 3.1.7 on 2021-04-18 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('permalink', models.CharField(blank=True, max_length=12, unique=True)),
                ('update_date', models.DateTimeField(verbose_name='Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('body', models.TextField(blank=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('', ''), ('html', 'HTML'), ('css', 'CSS'), ('bootstrap', 'BOOTSTRAP'), ('sass', 'SASS'), ('flexbox', 'FLEXBOX'), ('javascript', 'JAVASCRIPT'), ('jquery', 'JQUERY'), ('ajax', 'AJAX'), ('json', 'JSON'), ('react', 'REACT'), ('angular', 'ANGULAR'), ('nodejs', 'NODEJS'), ('vuejs', 'VUEJS'), ('graphql', 'GRAPHQL'), ('php', 'PHP'), ('laravel', 'LARAVEL'), ('python', 'PYTHON'), ('django', 'DJANGO'), ('numpy', 'NUMPY'), ('scipy', 'SCIPY'), ('pandas', 'PANDAS'), ('matplotlib', 'MATPLOTLIB'), ('tensorflow', 'TENSORFLOW'), ('scikitlearn', 'SCIKITLEARN'), ('keras', 'KERAS'), ('opencv', 'OPENCV'), ('tkinter', 'TKINTER'), ('qt', 'QT'), ('kivy', 'KIVY'), ('sql', 'SQL'), ('git', 'GIT')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
